version: "3.9"
services:
  app:
    image: aussidavid/monday_shareable_dashboard_frontend
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  proxy:
    external: true
    name: NPM_default
